#!/usr/bin/env bash
# WebProxyL — shared utilities

WPL_ROOT="${WPL_ROOT:-/opt/webproxyl}"
WPL_STATE_DIR="${WPL_STATE_DIR:-/etc/webproxyl}"
WPL_ENGINE_DIR="${WPL_ENGINE_DIR:-/opt/webproxyl/engine/tproxy-server}"
WPL_SITE_DIR="${WPL_SITE_DIR:-/srv/tproxy-site}"
WPL_LOG="${WPL_LOG:-/var/log/webproxyl.log}"
WPL_ENGINE_REPO="${WPL_ENGINE_REPO:-https://github.com/telegramdesktop/tproxy-server.git}"
WPL_ENGINE_REF="${WPL_ENGINE_REF:-master}"
WPL_GITHUB_REPO="${WPL_GITHUB_REPO:-RasmusVraa/WebProxyL}"

wpl_require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    wpl_err "Нужны права root. Запустите: sudo webproxyl $*"
    exit 1
  fi
}

wpl_arch_ok() {
  [[ "$(uname -m)" == "x86_64" ]]
}

wpl_load_state() {
  mkdir -p "$WPL_STATE_DIR"
  # shellcheck disable=SC1090
  [[ -f "${WPL_STATE_DIR}/settings.env" ]] && source "${WPL_STATE_DIR}/settings.env"
}

wpl_save_state() {
  mkdir -p "$WPL_STATE_DIR"
  umask 077
  cat >"${WPL_STATE_DIR}/settings.env" <<EOF
# Generated by WebProxyL — do not commit
WPL_HOSTNAME='${WPL_HOSTNAME:-}'
WPL_EMAIL='${WPL_EMAIL:-}'
WPL_SECRET='${WPL_SECRET:-}'
WPL_INSTALLED_AT='${WPL_INSTALLED_AT:-}'
WPL_ENGINE_REF='${WPL_ENGINE_REF:-master}'
WPL_MTPROXY_WORKERS='${WPL_MTPROXY_WORKERS:-1}'
WPL_MTPROXY_MAX_CONNECTIONS='${WPL_MTPROXY_MAX_CONNECTIONS:-4096}'
EOF
  chmod 600 "${WPL_STATE_DIR}/settings.env"
}

wpl_detect_public_ip() {
  local ip=""
  for url in \
    "https://api.ipify.org" \
    "https://ifconfig.me/ip" \
    "https://icanhazip.com"; do
    ip="$(curl -fsS --max-time 5 "$url" 2>/dev/null | tr -d '[:space:]' || true)"
    if [[ "$ip" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
      echo "$ip"
      return 0
    fi
  done
  return 1
}

wpl_gen_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 16
  else
    od -An -N16 -tx1 /dev/urandom | tr -d ' \n'
  fi
}

wpl_validate_hostname() {
  local h="$1"
  [[ "$h" =~ ^[a-z0-9]([a-z0-9.-]*[a-z0-9])?$ ]] && [[ "$h" == *.* ]]
}

wpl_validate_secret() {
  local s="$1"
  [[ "$s" =~ ^([0-9a-f]{32}|dd[0-9a-f]{32})$ ]]
}

wpl_validate_email() {
  local e="$1"
  [[ "$e" =~ ^[A-Za-z0-9._+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$ ]]
}

wpl_web_link() {
  local host="${1:-${WPL_HOSTNAME}}" secret="${2:-${WPL_SECRET}}"
  printf 'https://t.me/webproxy?server=%s&secret=%s\n' "$host" "$secret"
}

wpl_tg_link() {
  local host="${1:-${WPL_HOSTNAME}}" secret="${2:-${WPL_SECRET}}"
  printf 'tg://webproxy?server=%s&secret=%s\n' "$host" "$secret"
}

wpl_ensure_deps() {
  local pkgs=()
  command -v curl >/dev/null 2>&1 || pkgs+=(curl)
  command -v git >/dev/null 2>&1 || pkgs+=(git)
  command -v openssl >/dev/null 2>&1 || pkgs+=(openssl)
  command -v jq >/dev/null 2>&1 || pkgs+=(jq)
  [[ ${#pkgs[@]} -eq 0 ]] && return 0

  wpl_info "Устанавливаю зависимости: ${pkgs[*]}"
  export DEBIAN_FRONTEND=noninteractive
  if command -v apt-get >/dev/null 2>&1; then
    apt-get update -qq
    apt-get install -y -qq "${pkgs[@]}"
  elif command -v dnf >/dev/null 2>&1; then
    dnf install -y -q "${pkgs[@]}"
  elif command -v yum >/dev/null 2>&1; then
    yum install -y -q "${pkgs[@]}"
  else
    wpl_err "Не удалось установить: ${pkgs[*]}"
    return 1
  fi
}

wpl_service_state() {
  local unit="$1"
  if systemctl is-active --quiet "$unit" 2>/dev/null; then
    echo "active"
  elif systemctl is-enabled --quiet "$unit" 2>/dev/null; then
    echo "inactive"
  else
    echo "missing"
  fi
}

wpl_log() {
  mkdir -p "$(dirname "$WPL_LOG")"
  echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] $*" >>"$WPL_LOG"
}
