#!/usr/bin/env bash
# TgWebProxyR — shared utilities

TWPR_ROOT="${TWPR_ROOT:-/opt/tgwebproxyr}"
TWPR_STATE_DIR="${TWPR_STATE_DIR:-/etc/tgwebproxyr}"
TWPR_ENGINE_DIR="${TWPR_ENGINE_DIR:-/opt/tgwebproxyr/engine/tproxy-server}"
TWPR_SITE_DIR="${TWPR_SITE_DIR:-/srv/tproxy-site}"
TWPR_LOG="${TWPR_LOG:-/var/log/tgwebproxyr.log}"
TWPR_ENGINE_REPO="${TWPR_ENGINE_REPO:-https://github.com/telegramdesktop/tproxy-server.git}"
TWPR_ENGINE_REF="${TWPR_ENGINE_REF:-master}"
TWPR_GITHUB_REPO="${TWPR_GITHUB_REPO:-RasmusVraa/TgWebProxyR}"

TWPR_require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    TWPR_err "Нужны права root. Запустите: sudo tgwebproxyr $*"
    exit 1
  fi
}

TWPR_arch_ok() {
  [[ "$(uname -m)" == "x86_64" ]]
}

TWPR_load_state() {
  mkdir -p "$TWPR_STATE_DIR"
  # shellcheck disable=SC1090
  [[ -f "${TWPR_STATE_DIR}/settings.env" ]] && source "${TWPR_STATE_DIR}/settings.env"
}

TWPR_save_state() {
  mkdir -p "$TWPR_STATE_DIR"
  umask 077
  cat >"${TWPR_STATE_DIR}/settings.env" <<EOF
# Generated by TgWebProxyR — do not commit
TWPR_HOSTNAME='${TWPR_HOSTNAME:-}'
TWPR_EMAIL='${TWPR_EMAIL:-}'
TWPR_SECRET='${TWPR_SECRET:-}'
TWPR_INSTALLED_AT='${TWPR_INSTALLED_AT:-}'
TWPR_ENGINE_REF='${TWPR_ENGINE_REF:-master}'
TWPR_MTPROXY_WORKERS='${TWPR_MTPROXY_WORKERS:-1}'
TWPR_MTPROXY_MAX_CONNECTIONS='${TWPR_MTPROXY_MAX_CONNECTIONS:-4096}'
EOF
  chmod 600 "${TWPR_STATE_DIR}/settings.env"
}

TWPR_detect_public_ip() {
  local ip=""
  for url in \
    "https://api.ipify.org" \
    "https://ifconfig.me/ip" \
    "https://icanhazip.com"; do
    ip="$(curl -fsS --max-time 5 "$url" 2>/dev/null | tr -d '[:space:]' || true)"
    if [[ "$ip" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
      echo "$ip"
      return 0
    fi
  done
  return 1
}

TWPR_gen_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 16
  else
    od -An -N16 -tx1 /dev/urandom | tr -d ' \n'
  fi
}

TWPR_validate_hostname() {
  local h="$1"
  [[ "$h" =~ ^[a-z0-9]([a-z0-9.-]*[a-z0-9])?$ ]] && [[ "$h" == *.* ]]
}

TWPR_validate_secret() {
  local s="$1"
  [[ "$s" =~ ^([0-9a-f]{32}|dd[0-9a-f]{32})$ ]]
}

TWPR_validate_email() {
  local e="$1"
  [[ "$e" =~ ^[A-Za-z0-9._+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$ ]]
}

TWPR_web_link() {
  local host="${1:-${TWPR_HOSTNAME}}" secret="${2:-${TWPR_SECRET}}"
  printf 'https://t.me/webproxy?server=%s&secret=%s\n' "$host" "$secret"
}

TWPR_tg_link() {
  local host="${1:-${TWPR_HOSTNAME}}" secret="${2:-${TWPR_SECRET}}"
  printf 'tg://webproxy?server=%s&secret=%s\n' "$host" "$secret"
}

TWPR_ensure_deps() {
  local pkgs=()
  command -v curl >/dev/null 2>&1 || pkgs+=(curl)
  command -v git >/dev/null 2>&1 || pkgs+=(git)
  command -v openssl >/dev/null 2>&1 || pkgs+=(openssl)
  command -v jq >/dev/null 2>&1 || pkgs+=(jq)
  [[ ${#pkgs[@]} -eq 0 ]] && return 0

  TWPR_info "Устанавливаю зависимости: ${pkgs[*]}"
  export DEBIAN_FRONTEND=noninteractive
  if command -v apt-get >/dev/null 2>&1; then
    apt-get update -qq
    apt-get install -y -qq "${pkgs[@]}"
  elif command -v dnf >/dev/null 2>&1; then
    dnf install -y -q "${pkgs[@]}"
  elif command -v yum >/dev/null 2>&1; then
    yum install -y -q "${pkgs[@]}"
  else
    TWPR_err "Не удалось установить: ${pkgs[*]}"
    return 1
  fi
}

TWPR_service_state() {
  local unit="$1"
  if systemctl is-active --quiet "$unit" 2>/dev/null; then
    echo "active"
  elif systemctl is-enabled --quiet "$unit" 2>/dev/null; then
    echo "inactive"
  else
    echo "missing"
  fi
}

TWPR_log() {
  mkdir -p "$(dirname "$TWPR_LOG")"
  echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] $*" >>"$TWPR_LOG"
}
